### ISSUE TITLE
Firefox: missing Android support

### ISSUE THREAD

**Issue by emanuele6** [YujiSoftware/JavaAPI-Redirector#12]
Thank you for the add-on, it's awesome!

Can you please make the Firefox add-on android compatible?

**Comment by YujiSoftware** [comment]
Sorry, this add-on is not compatible with Firefox for Android.
This is because Firefox has limited functionality.

As soon as Firefox supports more add-ons, I'll do it. 

>#  Will more extensions be supported in the future?
> 
> We would like to enable support for more extensions on the new Firefox for Android experience and we are currently evaluating ways we can do so without introducing the compatibility and security issues from the previous version of our mobile browser for Android. We'll provide updates as soon as we have more details. 
> [Find and install Add-ons on Firefox for Android | Firefox for Android Help](https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android)

**Comment by emanuele6** [comment]
Oh, I did not know that.

I'll close the issue; thank you!
